using FreePIE.Core.Contracts;

namespace FreePIE.Plugin_Hook.Globals
{
    [GlobalEnum]
    public enum Key
    {
        Escape = 1,
        D1 = 2,
        D2,
        D3,
        D4,
        D5,
        D6,
        D7,
        D8,
        D9 = 10,
        D0 = 11,
        Minus = 12,
        Equals = 13,
        Back,
        Tab,
        Q = 16,
        W,
        E,
        R,
        T,
        Y,
        U,
        I,
        O,
        P = 25,
        LeftBracket,
        RightBracket,
        Return, Enter = Return,
        LeftControl, LCtrl = LeftControl,
        A = 30,
        S,
        D,
        F,
        G,
        H,
        J,
        K,
        L = 38,
        Semicolon,
        Apostrophe,
        Grave,
        LeftShift, LShft = LeftShift,
        Backslash,
        Z = 44,
        X,
        C,
        V,
        B,
        N,
        M = 50,
        Comma,
        Period,
        Slash,
        RightShift, RShft = RightShift,
        NumberPadStar,      // = Multiply,
        LeftAlt, LAlt = LeftAlt,
        Space,
        Capital,
        F1 = 59,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10 = 68,
        NumberLock,
        ScrollLock,
        NumberPad7 = 71,
        NumberPad8,
        NumberPad9 = 73,
        NumberPadMinus,     // = Subtract,
        NumberPad4 = 75,
        NumberPad5,
        NumberPad6 = 77,
        NumberPadPlus,      // = Add,
        NumberPad1 = 79,
        NumberPad2,
        NumberPad3,
        NumberPad0 = 82,
        NumberPadPeriod,    // = Decimal,
        Oem102 = 86,
        F11,
        F12,
        F13 = 100,
        F14,
        F15,
        Kana = 112,
        AbntC1 = 115,
        Convert = 121,
        NoConvert = 123,
        Yen = 125,
        AbntC2,
        NumberPadEquals = 141,
        PreviousTrack = 144,
        AT,
        Colon,
        Underline,
        Kanji,
        Stop,
        AX,
        Unlabeled,
        NextTrack = 153,
        NumberPadEnter = 156,
        RightControl, RCtrl = RightControl,
        Mute = 160,
        Calculator,
        PlayPause,
        MediaStop = 164,
        VolumeDown = 174,
        VolumeUp = 176,
        WebHome = 178,
        NumberPadComma,
        NumberPadSlash = 181,       // = Divide,
        PrintScreen = 183,
        RightAlt, RAlt = RightAlt,
        Pause = 197,
        Home = 199,
        UpArrow,            //Up
        PageUp,
        LeftArrow = 203,    //Left
        RightArrow = 205,   //Right
        End = 207,
        DownArrow,          //Down
        PageDown,
        Insert,
        Delete,
        LeftWindowsKey = 219, LWKey = LeftWindowsKey,
        RightWindowsKey, RWKey = RightWindowsKey,
        Applications,
        Power,
        Sleep,
        Wake = 227,
        WebSearch = 229,
        WebFavorites,
        WebRefresh,
        WebStop,
        WebForward,
        WebBack,
        MyComputer,
        Mail,
        MediaSelect, LastKey = MediaSelect,
        Unknown = 0
    }
    [GlobalEnum]
    public enum Mouse
    {
        Left = 238,
        Right,
        Middle,
        X1,
        X2,
        WheelFwd,
        WheelBwd, LastButton = WheelBwd,
        XY = 64 * 8,
        DragAndDrop = XY + 1,

    }
}