

namespace ZZTester
{
    // SlimDX key-codes

    //public enum Key
    //{
    //    None = -1,
    //    D0 = 0, D1 = 1, D2 = 2, D3 = 3, D4 = 4, D5 = 5, D6 = 6, D7 = 7, D8 = 8, D9 = 9,
    //    A = 10, B = 11, C = 12, D = 13, E = 14, F = 15, G = 16, H = 17, I = 18, J = 19,
    //    K = 20, L = 21, M = 22, N = 23, O = 24, P = 25, Q = 26, R = 27, S = 28, T = 29,
    //    U = 30, V = 31, W = 32, X = 33, Y = 34, Z = 35,
    //    /* Space, Semicolon, Comma = 38,
    //     NumberLock = 39,
    //     NumberPad0 = 40, NumberPad1, NumberPad2, NumberPad3, NumberPad4, NumberPad5,
    //     NumberPad6, NumberPad7, NumberPad8, NumberPad9 = 49,

    //     NumberPadMinus = 50, NumberPadPlus, NumberPadPeriod,  NumberPadSlash, NumberPadStar = 54,
    //     NumberPadComma, NumberPadEquals, 
    //     NumberPadEnter = 57,
    //     */
    //    AbntC1 = 36,                // 123  Semicolon
    //    AbntC2 = 37,                // 126  Space
    //    Apostrophe = 38,            // 47   Comma
    //    Applications = 39,          // 88   NumberLock
    //    AT = 40,                    // 89   NumberPad0
    //    AX = 41,                    // 90   NumberPad1
    //    Backspace = 42,             // 91   NumberPad2
    //    Backslash = 43,             // 92   NumberPad3
    //    Calculator = 44,            // 93   NumberPad4
    //    CapsLock = 45,              // 94   NumberPad5
    //    Colon = 46,                 // 95   NumberPad6
    //    Comma = 47,                 // 96   NumberPad7
    //    Convert = 48,               // 97   NumberPad8
    //    Delete = 49,                // 98   NumberPad9
    //    DownArrow = 50, End = 51, Equals = 52,
    //    Escape = 53,
    //    F1 = 54, F2 = 55, F3 = 56, F4 = 57, F5 = 58, F6 = 59, F7 = 60, F8 = 61, F9 = 62,
    //    F10 = 63, F11 = 64, F12 = 65, F13 = 66, F14 = 67, F15 = 68,
    //    Console = 69, Grave = Console, Exposant = Console,
    //    Home = 70,
    //    Insert = 71,
    //    Kana = 72,
    //    Kanji = 73,
    //    LeftBracket = 74,
    //    LeftControl = 75, LeftCtrl = LeftControl, LCtrl = LeftControl,
    //    LeftArrow = 76,
    //    LeftAlt = 77, LAlt = LeftAlt,
    //    LeftShift = 78, LSht = LeftShift,
    //    LeftWindowsKey = 79, LWKey = LeftWindowsKey,
    //    Mail = 80,
    //    MediaSelect = 81,
    //    MediaStop = 82,
    //    Minus = 83,
    //    Mute = 84,
    //    MyComputer = 85,
    //    NextTrack = 86,
    //    NoConvert = 87,
    //    NumberLock = 88,
    //    NumberPad0 = 89, NumberPad1 = 90, NumberPad2 = 91, NumberPad3 = 92, NumberPad4 = 93, NumberPad5 = 94,
    //    NumberPad6 = 95, NumberPad7 = 96, NumberPad8 = 97, NumberPad9 = 98, NumberPadComma = 99,
    //    NumberPadEnter = 100, NumberPadEquals = 101, NumberPadMinus = 102, NumberPadPeriod = 103, NumberPadPlus = 104, NumberPadSlash = 105, NumberPadStar = 106,
    //    Oem102 = 107,
    //    PageDown = 108, PageUp = 109,
    //    Pause = 110,
    //    Period = 111,
    //    PlayPause = 112,
    //    Power = 113,
    //    PreviousTrack = 114,
    //    RightBracket = 115,
    //    RightControl = 116, RightCtrl = RightControl, RCtrl = RightControl,
    //    Return = 117,
    //    RightArrow = 118,
    //    RightAlt = 119, RAlt = RightAlt,
    //    RightShift = 120, RSht = RightShift,
    //    RightWindowsKey = 121, RWKey = RightWindowsKey,
    //    ScrollLock = 122,
    //    Semicolon = 123,
    //    Slash = 124,
    //    Sleep = 125,
    //    Space = 126,
    //    Stop = 127,
    //    PrintScreen = 128,
    //    Tab = 129,
    //    Underline = 130,
    //    Unlabeled = 131,
    //    UpArrow = 132,
    //    VolumeDown = 133, VolumeUp = 134, Wake = 135,
    //    WebBack = 136, WebFavorites = 137, WebForward = 138, WebHome = 139, WebRefresh = 140, WebSearch = 141, WebStop = 142,
    //    Yen = 143,
    //    Unknown = 144,
    //    // AZERTY
    //    //    { (int)Key.A, (int)Key.Q},
    //    //    { (int)Key.Q, (int)Key.A},
    //    //    { (int)Key.Z, (int)Key.W},
    //    //    { (int)Key.W, (int)Key.Z},
    //    //    { (int)Key.Semicolon, (int)Key.M},
    //    //    { (int)Key.Comma, (int)Key.Semicolon},
    //    //    { (int)Key.M, (int)Key.Comma}
    //    aA = Q,
    //    aQ = A,
    //    aZ = W,
    //    aW = Z,
    //    aSemicolon = M,
    //    aComma = Semicolon,
    //    aM = Comma
    //}

    public enum Key
    {
        Escape = 1,
        D1 = 2,
        D2,
        D3,
        D4,
        D5,
        D6,
        D7,
        D8,
        D9 = 10,
        D0 = 11,
        Minus = 12,
        Equals = 13,
        Back,
        Tab,
        Q = 16,
        W,
        E,
        R,
        T,
        Y,
        U,
        I,
        O,
        P = 25,
        LeftBracket,
        RightBracket,
        Return,
        LeftControl, LCtrl = LeftControl,
        A = 30,
        S,
        D,
        F,
        G,
        H,
        J,
        K,
        L = 38,
        Semicolon,
        Apostrophe,
        Grave,
        LeftShift, LShft = LeftShift,
        Backslash,
        Z = 44,
        X,
        C,
        V,
        B,
        N,
        M = 50,
        Comma,
        Period,
        Slash,
        RightShift, RShft = RightShift,
        Multiply, NumberPadstar = Multiply,
        LeftAlt, LAlt = LeftAlt,
        Space,
        Capital,
        F1 = 59,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10 = 68,
        NumberLock,
        ScrollLock,
        NumberPad7 = 71,
        NumberPad8,
        NumberPad9 = 73,
        Subtract, NumberPadMinus = Subtract,
        NumberPad4 = 75,
        NumberPad5,
        NumberPad6 = 77,
        Add, NumberPadPlus = Add,
        NumberPad1 = 79,
        NumberPad2,
        NumberPad3,
        NumberPad0 = 82,
        Decimal,
        Oem102 = 86,
        F11,
        F12,
        F13 = 100,
        F14,
        F15,
        Kana = 112,
        AbntC1 = 115,
        Convert = 121,
        NoConvert = 123,
        Yen = 125,
        AbntC2,
        NumberPadEquals = 141,
        PreviousTrack = 144,
        AT,
        Colon,
        Underline,
        Kanji,
        Stop,
        AX,
        Unlabeled,
        NextTrack = 153,
        NumberPadEnter = 156,
        RightControl,
        Mute = 160,
        Calculator,
        PlayPause,
        MediaStop = 164,
        VolumeDown = 174,
        VolumeUp = 176,
        WebHome = 178,
        NumberPadComma,
        Divide = 181, NumberPadSlash = Divide,
        PrintScreen = 183,
        RightAlt, RAlt = RightAlt,
        Pause = 197,
        Home = 199,
        Up,
        PageUp,
        Left = 203,
        Right = 205,
        End = 207,
        Down,
        PageDown,
        Insert,
        Delete,
        LeftWindowsKey = 219, LWKey = LeftWindowsKey,
        RightWindowsKey, RWKey = RightWindowsKey,
        Applications,
        Power,
        Sleep,
        Wake = 227,
        WebSearch = 229,
        WebFavorites,
        WebRefresh,
        WebStop,
        WebForward,
        WebBack,
        MyComputer,
        Mail,
        MediaSelect,
        Unknown = 0,

        aA = Q,
        aQ = A,
        aZ = W,
        aW = Z,
        aSemicolon = M,
        aComma = Semicolon,
        aM = Comma,
    }

    public enum aKey
    {
        A = Key.Q,
        Q = Key.A,
        Z = Key.W,
        W = Key.Z,
        Semicolon = Key.M,
        Comma = Key.Semicolon,
        M = Key.Comma,
    }
    public enum Button
    {
        Left = 238,
        Right,
        Middle,
        X1,
        X2
    }
}
